CREATE DATABASE IF NOT EXISTS shelfspace
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE shelfspace;

CREATE TABLE Users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  passwordHash VARCHAR(255) NULL,
  role ENUM('USER','ADMIN') NOT NULL DEFAULT 'USER',
  isVerified BOOLEAN NOT NULL DEFAULT FALSE,
  authProvider ENUM('LOCAL','GOOGLE','FACEBOOK') NOT NULL DEFAULT 'LOCAL',
  providerId VARCHAR(255) NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_provider (authProvider, providerId)
);

CREATE TABLE UserOTPs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  otpHash VARCHAR(255) NOT NULL,
  purpose ENUM('PASSWORD_RESET','EMAIL_VERIFY') NOT NULL,
  attempts TINYINT NOT NULL DEFAULT 0,
  used BOOLEAN NOT NULL DEFAULT FALSE,
  expiresAt DATETIME NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_otp_user (userId, purpose),
  FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE RefreshTokens (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  tokenHash VARCHAR(255) NOT NULL,
  expiresAt DATETIME NOT NULL,
  revoked BOOLEAN NOT NULL DEFAULT FALSE,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_rt_user (userId),
  FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE
);

-- CATALOG
CREATE TABLE Authors (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  description TEXT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Genres (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  description TEXT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Books (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  authorId INT NOT NULL,
  description TEXT NULL,
  imageUrl VARCHAR(500) NULL,
  price DECIMAL(10,2) NOT NULL CHECK (price >= 0),
  releaseDate DATE NULL,
  stockQuantity INT NOT NULL DEFAULT 0 CHECK (stockQuantity >= 0),
  ratingAvg DECIMAL(3,2) NOT NULL DEFAULT 0,
  ratingCount INT NOT NULL DEFAULT 0,
  soldCount INT NOT NULL DEFAULT 0,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_book_title (title),
  FULLTEXT KEY ft_book_search (title, description),
  FOREIGN KEY (authorId) REFERENCES Authors(id)
);

CREATE TABLE BookGenres (
  bookId INT NOT NULL,
  genreId INT NOT NULL,
  PRIMARY KEY (bookId, genreId),
  FOREIGN KEY (bookId) REFERENCES Books(id) ON DELETE CASCADE,
  FOREIGN KEY (genreId) REFERENCES Genres(id) ON DELETE CASCADE
);

-- USER DATA
CREATE TABLE Addresses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  fullName VARCHAR(100) NOT NULL,
  phone VARCHAR(30) NULL,
  street VARCHAR(255) NOT NULL,
  city VARCHAR(100) NOT NULL,
  state VARCHAR(100) NOT NULL,
  country VARCHAR(100) NOT NULL,
  postalCode VARCHAR(20) NULL,
  isDefault BOOLEAN NOT NULL DEFAULT FALSE,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE PaymentMethods (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  provider VARCHAR(50) NOT NULL,
  brand VARCHAR(30) NULL,
  last4 CHAR(4) NULL,
  expiryMonth TINYINT NULL,
  expiryYear SMALLINT NULL,
  gatewayToken VARCHAR(255) NOT NULL,
  isDefault BOOLEAN NOT NULL DEFAULT FALSE,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE CartItems (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  bookId INT NOT NULL,
  quantity INT NOT NULL DEFAULT 1 CHECK (quantity > 0),
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_cart (userId, bookId),
  FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE,
  FOREIGN KEY (bookId) REFERENCES Books(id) ON DELETE CASCADE
);

CREATE TABLE WishlistItems (
  userId INT NOT NULL,
  bookId INT NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (userId, bookId),
  FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE,
  FOREIGN KEY (bookId) REFERENCES Books(id) ON DELETE CASCADE
);

-- ORDERS & PAYMENTS
CREATE TABLE Orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  totalAmount DECIMAL(10,2) NOT NULL,
  status ENUM('PENDING','PAID','PROCESSING','SHIPPED','OUT_FOR_DELIVERY','DELIVERED','CANCELLED')
    NOT NULL DEFAULT 'PENDING',
  trackingNumber VARCHAR(100) NULL,
  shippingName VARCHAR(100) NOT NULL,
  shippingPhone VARCHAR(30) NULL,
  shippingStreet VARCHAR(255) NOT NULL,
  shippingCity VARCHAR(100) NOT NULL,
  shippingState VARCHAR(100) NOT NULL,
  shippingCountry VARCHAR(100) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_order_user (userId),
  FOREIGN KEY (userId) REFERENCES Users(id)
);

CREATE TABLE OrderItems (
  id INT AUTO_INCREMENT PRIMARY KEY,
  orderId INT NOT NULL,
  bookId INT NULL,
  title VARCHAR(255) NOT NULL,
  quantity INT NOT NULL CHECK (quantity > 0),
  price DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (orderId) REFERENCES Orders(id) ON DELETE CASCADE,
  FOREIGN KEY (bookId) REFERENCES Books(id) ON DELETE SET NULL
);

CREATE TABLE OrderTracking (
  id INT AUTO_INCREMENT PRIMARY KEY,
  orderId INT NOT NULL,
  status ENUM('PENDING','PAID','PROCESSING','SHIPPED','OUT_FOR_DELIVERY','DELIVERED','CANCELLED') NOT NULL,
  note VARCHAR(255) NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_track_order (orderId),
  FOREIGN KEY (orderId) REFERENCES Orders(id) ON DELETE CASCADE
);

CREATE TABLE Payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  orderId INT NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  method ENUM('CARD','BANK_TRANSFER','PAY_ON_DELIVERY') NOT NULL,
  status ENUM('PENDING','SUCCESS','FAILED','REFUNDED') NOT NULL DEFAULT 'PENDING',
  reference VARCHAR(100) NULL UNIQUE,
  paidAt DATETIME NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_pay_order (orderId),
  FOREIGN KEY (orderId) REFERENCES Orders(id)
);

-- REVIEWS
CREATE TABLE Reviews (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  bookId INT NOT NULL,
  rating TINYINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment TEXT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_review (userId, bookId),
  FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE,
  FOREIGN KEY (bookId) REFERENCES Books(id) ON DELETE CASCADE
);

CREATE TABLE ReviewLikes (
  userId INT NOT NULL,
  reviewId INT NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (userId, reviewId),
  FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE,
  FOREIGN KEY (reviewId) REFERENCES Reviews(id) ON DELETE CASCADE
);


USE shelfspace;

ALTER TABLE Users
  ADD COLUMN phone VARCHAR(30) NOT NULL DEFAULT '' AFTER email,
  ADD COLUMN disabled BOOLEAN NOT NULL DEFAULT FALSE AFTER isVerified;

ALTER TABLE Books
  ADD COLUMN isBestseller BOOLEAN NOT NULL DEFAULT FALSE AFTER soldCount,
  ADD COLUMN isNewArrival BOOLEAN NOT NULL DEFAULT FALSE AFTER isBestseller,
  ADD COLUMN isFeatured BOOLEAN NOT NULL DEFAULT FALSE AFTER isNewArrival;

UPDATE Books
SET isBestseller = (soldCount >= 150),
    isFeatured   = (soldCount >= 200),
    isNewArrival = (COALESCE(releaseDate, DATE(createdAt)) >= DATE_SUB(CURDATE(), INTERVAL 90 DAY))
WHERE id > 0;